<h4>TÉRMINOS Y CONDICIONES </h4>
<p><strong>1. Adhesión.</strong> El proponente, de manera libre y voluntaria, se adhiere a los términos y condiciones aquí señalados. </p>
<p><strong>2. Medio formal de comunicaciones.</strong> Todos los actos relacionados a la subasta electrónica serán comunicados única y 
    exclusivamente a través del correo electrónico. </p>
<p><strong>3. Catálogo de Lotes y Bienes Recuperados Individuales.</strong> El proponente podrá consultar, a través del catálogo electrónico 
    alojado en el Portal Oficial de Subastas de UNIBIENES S.A., los Bienes Recuperados a subastarse, el plazo para la 
    recepción de ofertas y la ubicación de estas. </p>
<p><strong>4. Exhibición de las Bienes Recuperados a subastar.</strong> Los proponentes podrán observar las Bienes Recuperados 
    físicamente en los días y horas señalados en el Portal Oficial de Subastas de UNIBIENES S.A. de igual forma los 
    proponentes, deberán cumplir con las medidas de seguridad correspondientes, previo a su ingreso a los predios 
    almacenados por UNIBIENES S.A. donde se encuentren las Bienes Recuperados de su interés. </p>
<p><strong>5. Pago de Garantía.</strong> El proponente deberá realizar el depósito de garantía a la cuenta establecida de UNIBIENES S.A., a través de cualquiera de las entidades financieras correspondientes o mediante servicios de banca electrónica.</p>
<p><strong>6. Registro de Ofertas.</strong> Los proponentes registrarán sus ofertas a través del Portal Oficial de Subastas. Para los fines de adjudicación del Lote o Bien Recuperado Individual, únicamente serán consideradas las propuestas presentadas dentro del plazo establecido según convocatoria.</p>
<p><strong>7. Adjudicación.</strong> Será declarado ganador el proponente que haya ofertado el precio más alto por el Bien Recuperado a momento del cierre de ofertas en el Portal Oficial de Subastas.</p>
<p><strong>8. Pago de la Oferta por Bienes Recuperados.</strong> El proponente deberá realizar el pago del monto ofertado por el Bien Recuperado a la cuenta establecida por UNIBIENES S.A. a través de cualquier entidad financiera o mediante servicios de banca electrónica.</p>
<p>El pago de la oferta por el Bien Recuperado deberá realizarse en un plazo máximo de tres (3) días hábiles, computables a partir de la entrega de la nota de adjudicación al proponente. En caso que el proponente no realice el pago, le otorga a UNIBIENES S.A. la facultad para ejecutar la garantía depositada.</p>
<p><strong>9. Adjudicación.</strong> Realizado el pago del monto ofertado, UNIBIENES S.A. verificará y notificará la recepción del pago al proponente adjudicado, a través del correo electrónico, o cualquier otro medio verificable.</p>
<p><strong>10. Retiro de las Bienes Recuperados adjudicados.</strong> El proponente adjudicado deberá retirar las Bienes Recuperados adjudicados del almacén de UNIBIENES S.A. en un plazo no mayor a quince (15) días hábiles, computables a partir del cambio de nombre del bien sujeto a registro o notificación de recepción del pago (para bienes no sujetos a registro).</p>
<p>En caso de no retirar los bienes recuperados adjudicados dentro de los quince (15) días, se deberá pagar los costos de guardaje por día adicional computables desde el día hábil dieciséis (16). Si el Bien Recuperado no es retirado dentro de los treinta (30) días hábiles siguientes, el proponente adjudicado deberá abonar a cuentas de la Compañía un 3% adicional mensual del monto total de la adjudicación por incumplimiento a los plazos de retiro de los bienes recuperados adjudicados. Si los costos de guardaje y el porcentaje de abono por no recojo (incumplimiento a plazos de recojo) ascienden al monto de la oferta pagada por el bien recuperado adjudicado, el proponente acepta perder el derecho a la adjudicación del bien recuperado y UNIBIENES S.A. podrá disponer del bien recuperado no adjudicado.</p>
<p><strong>11. Privacidad de información.</strong> La información personal proporcionada por el proponente, tendrá carácter confidencial.</p>
<p><strong>12. Restricciones.</strong> UNIBIENES S.A. se reserva el derecho de aplicar restricciones a los proponentes ante la verificación de consulta en listas especiales o la evidencia de comportamientos prohibidos que afecten a los proponentes o intereses de UNIBIENES S.A.</p>
<p><strong>13. Responsabilidades.</strong> UNIBIENES S.A. no asume responsabilidad alguna por cualquier acción o perjuicio que pudiera resultar por la calidad, funcionalidad o información introducida en el Portal Oficial de Subastas y que pudieren derivar en la reprogramación de periodos de oferta, suspensión o finalización excepcional de la subasta.</p>
<p>El proponente acepta que al realizar transacciones vía internet con UNIBIENES S.A. lo hace bajo su propio riesgo, en ningún caso UNIBIENES S.A. se hace responsable por lucro cesante o por cualquier otro perjuicio que haya podido sufrir, debido a las transacciones realizadas o no realizadas.</p>
<p><strong>14. Devolución de Garantía.</strong> UNIBIENES S.A. procederá a la devolución del depósito de garantía al proponente no adjudicado en un plazo de siete (7) días hábiles aproximadamente.</p>
<p><strong>15. Soporte técnico para el uso del Portal Oficial de Subastas.</strong> El proponente podrá solicitar a UNIBIENES S.A., soporte técnico a través de los medios de contacto formales por problemas o errores en el uso del Portal Oficial de Subastas.</p>
<p><strong>16. Modificación.</strong> UNIBIENES S.A. podrá modificar los Términos y Condiciones sin previo aviso, siendo estos cambios aplicables a todas las operaciones efectuados en el Portal Oficial de la Subastas de UNIBIENES S.A. según el periodo de vigencia de los procesos.</p>
    